name: Publish Package to NPM
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. 1.0.1)'
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      packages: write      

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@zetxek'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update version if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ inputs.version }} --no-git-tag-version
        
      - name: Build
        run: npm run build

      - name: Verify versions match
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          GIT_TAG="${{ github.event_name == 'workflow_dispatch' && inputs.version || github.event.release.tag_name }}"
          GIT_TAG_CLEAN=${GIT_TAG#v}  # Remove 'v' prefix if present
          
          echo "Package version: $PKG_VERSION"
          echo "Git tag/Release version: $GIT_TAG_CLEAN"
          
          if [ "$PKG_VERSION" != "$GIT_TAG_CLEAN" ]; then
            echo "Error: Version mismatch!"
            echo "package.json version: $PKG_VERSION"
            echo "Git tag/Release version: $GIT_TAG_CLEAN"
            exit 1
          fi
          
          echo "✅ Versions match: $PKG_VERSION"
        
      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 