name: Test Theme Helper

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm test -- --coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage-final.json
        fail_ci_if_error: true

    - name: Comment PR with coverage
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          const coveragePath = path.join(process.cwd(), 'coverage', 'coverage-final.json');
          
          if (!fs.existsSync(coveragePath)) {
            console.error('Coverage file not found');
            return;
          }
          
          const coverage = require(coveragePath);
          if (!coverage || !coverage.total) {
            console.error('Invalid coverage data');
            return;
          }
          
          const total = coverage.total;
          const lines = total.lines?.pct || 0;
          const statements = total.statements?.pct || 0;
          const functions = total.functions?.pct || 0;
          const branches = total.branches?.pct || 0;
          
          const comment = `## Test Coverage Report
          
          Coverage results for this PR:
          
          | Category | Coverage |
          |---------|----------|
          | Lines | ${lines}% |
          | Statements | ${statements}% |
          | Functions | ${functions}% |
          | Branches | ${branches}% |
          
          View the full coverage report in the [Codecov dashboard](https://codecov.io/gh/${context.repo.owner}/${context.repo.repo}/pull/${context.issue.number}).`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          }); 